### ISSUE TITLE
npm 报错

### ISSUE THREAD

**Issue by zhaozhe0831** [coder-Yin/learn-vue#1]
zhaozhedeiMac:learn-vue zhaozhe$ npm run dev

> vue_js@1.0.0 dev /Users/zhaozhe/Work/vue/learn-vue
> webpack-dev-server --hot --quiet

sh: webpack-dev-server: command not found

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v4.3.1
npm ERR! npm  v3.8.1
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! vue_js@1.0.0 dev: `webpack-dev-server --hot --quiet`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the vue_js@1.0.0 dev script 'webpack-dev-server --hot --quiet'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vue_js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --hot --quiet
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vue_js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vue_js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/zhaozhe/Work/vue/learn-vue/npm-debug.log
zhaozhedeiMac:learn-vue zhaozhe$

**Comment by coder-Yin** [comment]
npm install webpack-dev-server
